# fix: true               # default: false
parallel: true # default: false
format: progress # default: Standard::Formatter
default_ignores: false # default: true

ignore: # default: []
  - "db/**/*"
  - "vendor/**/*"
  - "config/**/*"
  - "script/**/*"
  - "test/**/*"
  - "bin/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "coverage/**/*"
  - "log/**/*"
