require "dotenv/load"

require "net/http"
require "json"

require_relative "core_ext/string"

# require_relative "business_central/client"
require_relative "business_central/version"
require_relative "business_central/errors"

module BusinessCentral
  API_PATH = "/api/v2.0"
  API_VERSION = "/v2.0"
  ENDPOINT_TEST = "https://wiise.api.bc.dynamics.com"
  ENDPOINT_PRODUCTION = "https://wiise.api.bc.dynamics.com"

  autoload :Client, "business_central/client"
  autoload :ApiMethods, "business_central/api_methods"
  autoload :Base, "business_central/base"
  autoload :RequestBuilder, "business_central/request_builder"
  autoload :URLBuilder, "business_central/url_builder"

  autoload :Account, "business_central/account"
  autoload :AgedAccountsPayable, "business_central/aged_accounts_payable"
  autoload :AgedAccountsReceivable, "business_central/aged_accounts_receivable"
  autoload :BalanceSheet, "business_central/balance_sheet"
  autoload :CashFlowStatement, "business_central/cash_flow_statement"
  autoload :Company, "business_central/company"
  autoload :CompanyInformation, "business_central/company_information"
  autoload :CountriesRegion, "business_central/countries_region"
  autoload :Currency, "business_central/currency"
  autoload :Customer, "business_central/customer"
  autoload :CustomerFinancialDetails, "business_central/customer_financial_details"
  autoload :CustomerPayment, "business_central/customer_payment"
  autoload :CustomerPaymentsJournal, "business_central/customer_payments_journal"
  autoload :CustomerSales, "business_central/customer_sales"
  autoload :Dimension, "business_central/dimension"
  autoload :DimensionLine, "business_central/dimension_line"
  autoload :Employee, "business_central/employee"
  autoload :GeneralLedgerEntry, "business_central/general_ledger_entry"
  autoload :IncomeStatement, "business_central/income_statement"
  autoload :Irs1099Code, "business_central/irs_1099_code"
  autoload :Item, "business_central/item"
  autoload :ItemCategory, "business_central/item_category"
  autoload :Journal, "business_central/journal"
  autoload :JournalLine, "business_central/journal_line"
  autoload :PaymentMethod, "business_central/payment_method"
  autoload :PaymentTerm, "business_central/payment_term"
  autoload :Picture, "business_central/picture"
  autoload :PurchaseInvoice, "business_central/purchase_invoice"
  autoload :PurchaseInvoiceLine, "business_central/purchase_invoice_line"
  autoload :RetainedEarningsStatement, "business_central/retained_earnings_statement"
  autoload :SalesCreditMemo, "business_central/sales_credit_memo"
  autoload :SalesCreditMemoLine, "business_central/sales_credit_memo_line"
  autoload :SalesInvoice, "business_central/sales_invoice"
  autoload :SalesInvoiceLine, "business_central/sales_invoice_line"
  autoload :SalesOrder, "business_central/sales_order"
  autoload :SalesOrderLine, "business_central/sales_order_line"
  autoload :SalesQuote, "business_central/sales_quote"
  autoload :SalesQuoteLine, "business_central/sales_quote_line"
  autoload :ShipmentMethod, "business_central/shipment_method"
  autoload :Subscription, "business_central/subscription"
  autoload :TaxArea, "business_central/tax_area"
  autoload :TaxGroup, "business_central/tax_group"
  autoload :TrialBalance, "business_central/trial_balance"
  autoload :UnitOfMeasure, "business_central/unit_of_measure"
  autoload :Vendor, "business_central/vendor"
  autoload :VendorPurchase, "business_central/vendor_purchase"

  module Response
    autoload :ResponseHandler, "business_central/response/response_handler"
  end
end
